Search feature
akolotly/book_exchange pull request #5
Opened 2018-06-01 16:40 UTC by akolotly

https://trello.com/c/UK6ml17d/7-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%B8%D1%82%D1%8C-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%83-%D0%BF%D0%BE-%D0%BE%D0%B1%D0%BC%D0%B5%D0%BD%D1%83-%D0%BA%D0%BD%D0%B8%D0%B3

2018-06-04 09:04 UTC, thepry approved these changes

2018-06-04 09:48 UTC, thktomska requested changes
Все отлично - кроме исопльзования тега не по назначению - поправсь плиз и выкатывай

2018-06-04 09:48 UTC, thktomska commented on app/views/books/index.html.slim
> +  p.margin-bottom-30
использоать p тэг для отступов - плохая практика - нужно задать кастомные стили для кастомных классов (не бутстрапом единым)

2018-06-05 08:06 UTC, thktomska approved these changes
https://www.youtube.com/watch?v=-yNhl8wT3Pc

2018-06-05 08:07 UTC, merged